Revert "arch/arm64: fix -mcpu target for Kryo 385 (SDM845)"
Causes:

Error: unknown architectural extension `dotprod'
Error: unrecognized option -mcpu=cortex-a75+crypto+crc+nodotprod
clang-12: error: assembler command failed with exit code 1 (use -v to see invocation)
make[2]: *** [/home/jenkins/workspace/source/android/aicp/r11.1/kernel/xiaomi/sdm845/scripts/Makefile.build:342: arch/arm64/crypto/aes-ce-cipher-core.o] Error 1
make[1]: *** [/home/jenkins/workspace/source/android/aicp/r11.1/kernel/xiaomi/sdm845/Makefile:1156: arch/arm64/crypto] Error 2

This reverts commit 01d6eed2dfc805dca39f60ba72092876f4004d0b.

Change-Id: Idc1f6c9b17370a5e6310691b5dbe096192d757a2
Signed-off-by: Semavi Ulusoy <doc.divxm@gmail.com>